In [28]:
import pandas as pd
import matplotlib.pyplot as plt 
import matplotlib.ticker as mticker 
from matplotlib.backends.backend_pdf import PdfPages

c = pd.read_csv('customers_cleaned.csv')

In [29]:
c['age_group'] = pd.cut(c['age'],bins=[17, 24, 34, 44, 1000], labels=['18-24', '25-34', '35-44', '45+'])
agecount = c['age_group'].value_counts().sort_index()
print(agecount)

age_group
18-24     78
25-34    118
35-44    123
45+      401
Name: count, dtype: int64

In [30]:
gendercount = c[c['gender'].isin(['M','F'])]['gender'].value_counts()
genderpct = (gendercount / gendercount.sum() * 100).round(2)
genderdf = pd.DataFrame({'Gender': genderpct.index, 'Percentage (%)': genderpct.values})
display(genderdf)

  Gender  Percentage (%)
0      M           50.77
1      F           49.23

In [31]:
c['membership_status'] = c['membership_status'].str.title()

tier = c[c['membership_status'].isin({'Basic','Silver','Gold'})]

avgspend = (tier.groupby('membership_status')['total_spending'].mean().round(2).reindex(['Basic','Silver','Gold']))
tierdf = pd.DataFrame({'Tier': avgspend.index, 'Avg Spending ($)' : avgspend.values})
display(tierdf)

     Tier  Avg Spending ($)
0   Basic          44130.41
1  Silver          83806.55
2    Gold          72854.51