In [2]:
import pandas as pd, warnings; warnings.filterwarnings('ignore')
s = pd.read_csv('sales_transactions_cleaned.csv')
s['revenue'] =  (s['quantity']*s['price'])- pd.to_numeric(s['discount_amount'],errors='coerce').fillna(0)
s['date'] = pd.to_datetime(s['date'])

cust = s.groupby('customer_id').agg(total_revenue = ('revenue', 'sum'), total_tx = ('transaction_id','nunique')).reset_index()
cust['average_purchase_value'] = cust['total_revenue'] / cust['total_tx']
display(cust)

     customer_id  total_revenue  total_tx  average_purchase_value
0            101         110.30        13                8.484615
1            102         328.36        17               19.315294
2            103         529.39        22               24.063182
3            104         173.46        21                8.260000
4            105         150.07        11               13.642727
..           ...            ...       ...                     ...
615          716         108.73        12                9.060833
616          717         363.18        28               12.970714
617          718         102.60        13                7.892308
618          719         271.98        19               14.314737
619          720          95.62        10                9.562000

[620 rows x 4 columns]

In [3]:
total_month = s['date'].dt.to_period('M').nunique()
cust['purchase_frequency'] = cust['total_tx'] / total_month

cust['cltv'] = (cust['average_purchase_value'] * cust['purchase_frequency'] * 36).round(2)

result = cust[['customer_id','cltv']].copy()
result['customer_id'] = result['customer_id'].astype(int)
display(result)

     customer_id     cltv
0            101   397.08
1            102  1182.10
2            103  1905.80
3            104   624.46
4            105   540.25
..           ...      ...
615          716   391.43
616          717  1307.45
617          718   369.36
618          719   979.13
619          720   344.23

[620 rows x 2 columns]

In [4]:
result.to_csv('Session1_CLTVVTest.csv', index=False)
print('Success')

Success